<?php
/**
 * User
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Tripartie\Tpdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Tripartie
 *
 * Our API suite for the **Resolution Center** and the **Safe Checkout** features. Simple, yet elegant web interfaces for your convenience. One request away from your first automated resolution or safe-checkout.
 *
 * The version of the OpenAPI document: 2.0.29
 * Contact: noc@tripartie.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Tripartie\Tpdk\Model;

use \ArrayAccess;
use \Tripartie\Tpdk\ObjectSerializer;

/**
 * User Class Doc Comment
 *
 * @category Class
 * @description 
 * @package  Tripartie\Tpdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class User implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'User';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'captcha' => 'string',
        'firstName' => 'string',
        'lastName' => 'string',
        'publicName' => 'string',
        'roleInCompany' => 'string',
        'birthday' => '\DateTime',
        'email' => 'string',
        'roles' => 'string[]',
        'password' => 'string',
        'plainPassword' => 'string',
        'intlPhoneNumber' => 'string',
        'originCountry' => 'string',
        'preferredLanguage' => 'string',
        'lastSuccessfulLogIn' => '\DateTime',
        'emailVerificationCode' => 'string',
        'emailVerificationInput' => 'string',
        'phoneVerificationCode' => 'string',
        'phoneVerificationInput' => 'string',
        'avatar' => 'string',
        'notifications' => 'string[]',
        'medias' => 'string[]',
        'views' => '\Tripartie\Tpdk\Model\View[]',
        'createdAt' => '\DateTime',
        'updatedAt' => '\DateTime',
        'consentMailNotification' => 'bool',
        'consentMailAds' => 'bool',
        'keys' => 'string[]',
        'organization' => 'string',
        'username' => 'string',
        'salt' => 'string',
        'userIdentifier' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => 'iri-reference',
        'captcha' => null,
        'firstName' => null,
        'lastName' => null,
        'publicName' => null,
        'roleInCompany' => null,
        'birthday' => 'date-time',
        'email' => null,
        'roles' => null,
        'password' => null,
        'plainPassword' => null,
        'intlPhoneNumber' => null,
        'originCountry' => null,
        'preferredLanguage' => null,
        'lastSuccessfulLogIn' => 'date-time',
        'emailVerificationCode' => null,
        'emailVerificationInput' => null,
        'phoneVerificationCode' => null,
        'phoneVerificationInput' => null,
        'avatar' => 'iri-reference',
        'notifications' => 'iri-reference',
        'medias' => 'iri-reference',
        'views' => null,
        'createdAt' => 'date-time',
        'updatedAt' => 'date-time',
        'consentMailNotification' => null,
        'consentMailAds' => null,
        'keys' => 'iri-reference',
        'organization' => 'iri-reference',
        'username' => null,
        'salt' => null,
        'userIdentifier' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
		'captcha' => true,
		'firstName' => false,
		'lastName' => false,
		'publicName' => true,
		'roleInCompany' => true,
		'birthday' => false,
		'email' => false,
		'roles' => false,
		'password' => false,
		'plainPassword' => true,
		'intlPhoneNumber' => true,
		'originCountry' => false,
		'preferredLanguage' => false,
		'lastSuccessfulLogIn' => true,
		'emailVerificationCode' => true,
		'emailVerificationInput' => true,
		'phoneVerificationCode' => true,
		'phoneVerificationInput' => true,
		'avatar' => true,
		'notifications' => false,
		'medias' => false,
		'views' => false,
		'createdAt' => false,
		'updatedAt' => false,
		'consentMailNotification' => false,
		'consentMailAds' => false,
		'keys' => false,
		'organization' => true,
		'username' => false,
		'salt' => true,
		'userIdentifier' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'captcha' => 'captcha',
        'firstName' => 'firstName',
        'lastName' => 'lastName',
        'publicName' => 'publicName',
        'roleInCompany' => 'roleInCompany',
        'birthday' => 'birthday',
        'email' => 'email',
        'roles' => 'roles',
        'password' => 'password',
        'plainPassword' => 'plainPassword',
        'intlPhoneNumber' => 'intlPhoneNumber',
        'originCountry' => 'originCountry',
        'preferredLanguage' => 'preferredLanguage',
        'lastSuccessfulLogIn' => 'lastSuccessfulLogIn',
        'emailVerificationCode' => 'emailVerificationCode',
        'emailVerificationInput' => 'emailVerificationInput',
        'phoneVerificationCode' => 'phoneVerificationCode',
        'phoneVerificationInput' => 'phoneVerificationInput',
        'avatar' => 'avatar',
        'notifications' => 'notifications',
        'medias' => 'medias',
        'views' => 'views',
        'createdAt' => 'createdAt',
        'updatedAt' => 'updatedAt',
        'consentMailNotification' => 'consentMailNotification',
        'consentMailAds' => 'consentMailAds',
        'keys' => 'keys',
        'organization' => 'organization',
        'username' => 'username',
        'salt' => 'salt',
        'userIdentifier' => 'userIdentifier'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'captcha' => 'setCaptcha',
        'firstName' => 'setFirstName',
        'lastName' => 'setLastName',
        'publicName' => 'setPublicName',
        'roleInCompany' => 'setRoleInCompany',
        'birthday' => 'setBirthday',
        'email' => 'setEmail',
        'roles' => 'setRoles',
        'password' => 'setPassword',
        'plainPassword' => 'setPlainPassword',
        'intlPhoneNumber' => 'setIntlPhoneNumber',
        'originCountry' => 'setOriginCountry',
        'preferredLanguage' => 'setPreferredLanguage',
        'lastSuccessfulLogIn' => 'setLastSuccessfulLogIn',
        'emailVerificationCode' => 'setEmailVerificationCode',
        'emailVerificationInput' => 'setEmailVerificationInput',
        'phoneVerificationCode' => 'setPhoneVerificationCode',
        'phoneVerificationInput' => 'setPhoneVerificationInput',
        'avatar' => 'setAvatar',
        'notifications' => 'setNotifications',
        'medias' => 'setMedias',
        'views' => 'setViews',
        'createdAt' => 'setCreatedAt',
        'updatedAt' => 'setUpdatedAt',
        'consentMailNotification' => 'setConsentMailNotification',
        'consentMailAds' => 'setConsentMailAds',
        'keys' => 'setKeys',
        'organization' => 'setOrganization',
        'username' => 'setUsername',
        'salt' => 'setSalt',
        'userIdentifier' => 'setUserIdentifier'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'captcha' => 'getCaptcha',
        'firstName' => 'getFirstName',
        'lastName' => 'getLastName',
        'publicName' => 'getPublicName',
        'roleInCompany' => 'getRoleInCompany',
        'birthday' => 'getBirthday',
        'email' => 'getEmail',
        'roles' => 'getRoles',
        'password' => 'getPassword',
        'plainPassword' => 'getPlainPassword',
        'intlPhoneNumber' => 'getIntlPhoneNumber',
        'originCountry' => 'getOriginCountry',
        'preferredLanguage' => 'getPreferredLanguage',
        'lastSuccessfulLogIn' => 'getLastSuccessfulLogIn',
        'emailVerificationCode' => 'getEmailVerificationCode',
        'emailVerificationInput' => 'getEmailVerificationInput',
        'phoneVerificationCode' => 'getPhoneVerificationCode',
        'phoneVerificationInput' => 'getPhoneVerificationInput',
        'avatar' => 'getAvatar',
        'notifications' => 'getNotifications',
        'medias' => 'getMedias',
        'views' => 'getViews',
        'createdAt' => 'getCreatedAt',
        'updatedAt' => 'getUpdatedAt',
        'consentMailNotification' => 'getConsentMailNotification',
        'consentMailAds' => 'getConsentMailAds',
        'keys' => 'getKeys',
        'organization' => 'getOrganization',
        'username' => 'getUsername',
        'salt' => 'getSalt',
        'userIdentifier' => 'getUserIdentifier'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const ROLES_ORGANIZATION_OWNER = 'ROLE_ORGANIZATION_OWNER';
    public const ROLES_ADMIN = 'ROLE_ADMIN';
    public const ROLES_CONSULTANT = 'ROLE_CONSULTANT';
    public const ROLES_ACCOUNTING_MANAGER = 'ROLE_ACCOUNTING_MANAGER';
    public const ROLES_BILLING_MANAGER = 'ROLE_BILLING_MANAGER';
    public const ROLES_CUSTOMER_SERVICE = 'ROLE_CUSTOMER_SERVICE';
    public const ROLES_PLATFORM_SUPPORT = 'ROLE_PLATFORM_SUPPORT';
    public const ROLES_PLATFORM_ADMIN = 'ROLE_PLATFORM_ADMIN';
    public const ROLES_USER = 'ROLE_USER';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getRolesAllowableValues()
    {
        return [
            self::ROLES_ORGANIZATION_OWNER,
            self::ROLES_ADMIN,
            self::ROLES_CONSULTANT,
            self::ROLES_ACCOUNTING_MANAGER,
            self::ROLES_BILLING_MANAGER,
            self::ROLES_CUSTOMER_SERVICE,
            self::ROLES_PLATFORM_SUPPORT,
            self::ROLES_PLATFORM_ADMIN,
            self::ROLES_USER,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('captcha', $data ?? [], null);
        $this->setIfExists('firstName', $data ?? [], null);
        $this->setIfExists('lastName', $data ?? [], null);
        $this->setIfExists('publicName', $data ?? [], null);
        $this->setIfExists('roleInCompany', $data ?? [], null);
        $this->setIfExists('birthday', $data ?? [], null);
        $this->setIfExists('email', $data ?? [], null);
        $this->setIfExists('roles', $data ?? [], null);
        $this->setIfExists('password', $data ?? [], null);
        $this->setIfExists('plainPassword', $data ?? [], null);
        $this->setIfExists('intlPhoneNumber', $data ?? [], null);
        $this->setIfExists('originCountry', $data ?? [], null);
        $this->setIfExists('preferredLanguage', $data ?? [], null);
        $this->setIfExists('lastSuccessfulLogIn', $data ?? [], null);
        $this->setIfExists('emailVerificationCode', $data ?? [], null);
        $this->setIfExists('emailVerificationInput', $data ?? [], null);
        $this->setIfExists('phoneVerificationCode', $data ?? [], null);
        $this->setIfExists('phoneVerificationInput', $data ?? [], null);
        $this->setIfExists('avatar', $data ?? [], null);
        $this->setIfExists('notifications', $data ?? [], null);
        $this->setIfExists('medias', $data ?? [], null);
        $this->setIfExists('views', $data ?? [], null);
        $this->setIfExists('createdAt', $data ?? [], null);
        $this->setIfExists('updatedAt', $data ?? [], null);
        $this->setIfExists('consentMailNotification', $data ?? [], null);
        $this->setIfExists('consentMailAds', $data ?? [], null);
        $this->setIfExists('keys', $data ?? [], null);
        $this->setIfExists('organization', $data ?? [], null);
        $this->setIfExists('username', $data ?? [], null);
        $this->setIfExists('salt', $data ?? [], null);
        $this->setIfExists('userIdentifier', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['birthday'] === null) {
            $invalidProperties[] = "'birthday' can't be null";
        }
        if ($this->container['roles'] === null) {
            $invalidProperties[] = "'roles' can't be null";
        }
        if ($this->container['password'] === null) {
            $invalidProperties[] = "'password' can't be null";
        }
        if (!is_null($this->container['originCountry']) && (mb_strlen($this->container['originCountry']) > 3)) {
            $invalidProperties[] = "invalid value for 'originCountry', the character length must be smaller than or equal to 3.";
        }

        if (!is_null($this->container['preferredLanguage']) && (mb_strlen($this->container['preferredLanguage']) > 2)) {
            $invalidProperties[] = "invalid value for 'preferredLanguage', the character length must be smaller than or equal to 2.";
        }

        if ($this->container['views'] === null) {
            $invalidProperties[] = "'views' can't be null";
        }
        if ($this->container['consentMailNotification'] === null) {
            $invalidProperties[] = "'consentMailNotification' can't be null";
        }
        if ($this->container['consentMailAds'] === null) {
            $invalidProperties[] = "'consentMailAds' can't be null";
        }
        if ($this->container['keys'] === null) {
            $invalidProperties[] = "'keys' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets captcha
     *
     * @return string|null
     */
    public function getCaptcha()
    {
        return $this->container['captcha'];
    }

    /**
     * Sets captcha
     *
     * @param string|null $captcha captcha
     *
     * @return self
     */
    public function setCaptcha($captcha)
    {
        if (is_null($captcha)) {
            array_push($this->openAPINullablesSetToNull, 'captcha');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('captcha', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['captcha'] = $captcha;

        return $this;
    }

    /**
     * Gets firstName
     *
     * @return string|null
     */
    public function getFirstName()
    {
        return $this->container['firstName'];
    }

    /**
     * Sets firstName
     *
     * @param string|null $firstName firstName
     *
     * @return self
     */
    public function setFirstName($firstName)
    {
        if (is_null($firstName)) {
            throw new \InvalidArgumentException('non-nullable firstName cannot be null');
        }
        $this->container['firstName'] = $firstName;

        return $this;
    }

    /**
     * Gets lastName
     *
     * @return string|null
     */
    public function getLastName()
    {
        return $this->container['lastName'];
    }

    /**
     * Sets lastName
     *
     * @param string|null $lastName lastName
     *
     * @return self
     */
    public function setLastName($lastName)
    {
        if (is_null($lastName)) {
            throw new \InvalidArgumentException('non-nullable lastName cannot be null');
        }
        $this->container['lastName'] = $lastName;

        return $this;
    }

    /**
     * Gets publicName
     *
     * @return string|null
     */
    public function getPublicName()
    {
        return $this->container['publicName'];
    }

    /**
     * Sets publicName
     *
     * @param string|null $publicName publicName
     *
     * @return self
     */
    public function setPublicName($publicName)
    {
        if (is_null($publicName)) {
            array_push($this->openAPINullablesSetToNull, 'publicName');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('publicName', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['publicName'] = $publicName;

        return $this;
    }

    /**
     * Gets roleInCompany
     *
     * @return string|null
     */
    public function getRoleInCompany()
    {
        return $this->container['roleInCompany'];
    }

    /**
     * Sets roleInCompany
     *
     * @param string|null $roleInCompany roleInCompany
     *
     * @return self
     */
    public function setRoleInCompany($roleInCompany)
    {
        if (is_null($roleInCompany)) {
            array_push($this->openAPINullablesSetToNull, 'roleInCompany');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('roleInCompany', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['roleInCompany'] = $roleInCompany;

        return $this;
    }

    /**
     * Gets birthday
     *
     * @return \DateTime
     */
    public function getBirthday()
    {
        return $this->container['birthday'];
    }

    /**
     * Sets birthday
     *
     * @param \DateTime $birthday birthday
     *
     * @return self
     */
    public function setBirthday($birthday)
    {
        if (is_null($birthday)) {
            throw new \InvalidArgumentException('non-nullable birthday cannot be null');
        }
        $this->container['birthday'] = $birthday;

        return $this;
    }

    /**
     * Gets email
     *
     * @return string|null
     */
    public function getEmail()
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     *
     * @param string|null $email email
     *
     * @return self
     */
    public function setEmail($email)
    {
        if (is_null($email)) {
            throw new \InvalidArgumentException('non-nullable email cannot be null');
        }
        $this->container['email'] = $email;

        return $this;
    }

    /**
     * Gets roles
     *
     * @return string[]
     */
    public function getRoles()
    {
        return $this->container['roles'];
    }

    /**
     * Sets roles
     *
     * @param string[] $roles roles
     *
     * @return self
     */
    public function setRoles($roles)
    {
        if (is_null($roles)) {
            throw new \InvalidArgumentException('non-nullable roles cannot be null');
        }
        $allowedValues = $this->getRolesAllowableValues();
        if (array_diff($roles, $allowedValues)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'roles', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['roles'] = $roles;

        return $this;
    }

    /**
     * Gets password
     *
     * @return string
     */
    public function getPassword()
    {
        return $this->container['password'];
    }

    /**
     * Sets password
     *
     * @param string $password The hashed password
     *
     * @return self
     */
    public function setPassword($password)
    {
        if (is_null($password)) {
            throw new \InvalidArgumentException('non-nullable password cannot be null');
        }
        $this->container['password'] = $password;

        return $this;
    }

    /**
     * Gets plainPassword
     *
     * @return string|null
     */
    public function getPlainPassword()
    {
        return $this->container['plainPassword'];
    }

    /**
     * Sets plainPassword
     *
     * @param string|null $plainPassword plainPassword
     *
     * @return self
     */
    public function setPlainPassword($plainPassword)
    {
        if (is_null($plainPassword)) {
            array_push($this->openAPINullablesSetToNull, 'plainPassword');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('plainPassword', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['plainPassword'] = $plainPassword;

        return $this;
    }

    /**
     * Gets intlPhoneNumber
     *
     * @return string|null
     */
    public function getIntlPhoneNumber()
    {
        return $this->container['intlPhoneNumber'];
    }

    /**
     * Sets intlPhoneNumber
     *
     * @param string|null $intlPhoneNumber intlPhoneNumber
     *
     * @return self
     */
    public function setIntlPhoneNumber($intlPhoneNumber)
    {
        if (is_null($intlPhoneNumber)) {
            array_push($this->openAPINullablesSetToNull, 'intlPhoneNumber');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('intlPhoneNumber', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['intlPhoneNumber'] = $intlPhoneNumber;

        return $this;
    }

    /**
     * Gets originCountry
     *
     * @return string|null
     */
    public function getOriginCountry()
    {
        return $this->container['originCountry'];
    }

    /**
     * Sets originCountry
     *
     * @param string|null $originCountry The originating country
     *
     * @return self
     */
    public function setOriginCountry($originCountry)
    {
        if (is_null($originCountry)) {
            throw new \InvalidArgumentException('non-nullable originCountry cannot be null');
        }
        if ((mb_strlen($originCountry) > 3)) {
            throw new \InvalidArgumentException('invalid length for $originCountry when calling User., must be smaller than or equal to 3.');
        }

        $this->container['originCountry'] = $originCountry;

        return $this;
    }

    /**
     * Gets preferredLanguage
     *
     * @return string|null
     */
    public function getPreferredLanguage()
    {
        return $this->container['preferredLanguage'];
    }

    /**
     * Sets preferredLanguage
     *
     * @param string|null $preferredLanguage preferredLanguage
     *
     * @return self
     */
    public function setPreferredLanguage($preferredLanguage)
    {
        if (is_null($preferredLanguage)) {
            throw new \InvalidArgumentException('non-nullable preferredLanguage cannot be null');
        }
        if ((mb_strlen($preferredLanguage) > 2)) {
            throw new \InvalidArgumentException('invalid length for $preferredLanguage when calling User., must be smaller than or equal to 2.');
        }

        $this->container['preferredLanguage'] = $preferredLanguage;

        return $this;
    }

    /**
     * Gets lastSuccessfulLogIn
     *
     * @return \DateTime|null
     */
    public function getLastSuccessfulLogIn()
    {
        return $this->container['lastSuccessfulLogIn'];
    }

    /**
     * Sets lastSuccessfulLogIn
     *
     * @param \DateTime|null $lastSuccessfulLogIn lastSuccessfulLogIn
     *
     * @return self
     */
    public function setLastSuccessfulLogIn($lastSuccessfulLogIn)
    {
        if (is_null($lastSuccessfulLogIn)) {
            array_push($this->openAPINullablesSetToNull, 'lastSuccessfulLogIn');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('lastSuccessfulLogIn', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['lastSuccessfulLogIn'] = $lastSuccessfulLogIn;

        return $this;
    }

    /**
     * Gets emailVerificationCode
     *
     * @return string|null
     */
    public function getEmailVerificationCode()
    {
        return $this->container['emailVerificationCode'];
    }

    /**
     * Sets emailVerificationCode
     *
     * @param string|null $emailVerificationCode emailVerificationCode
     *
     * @return self
     */
    public function setEmailVerificationCode($emailVerificationCode)
    {
        if (is_null($emailVerificationCode)) {
            array_push($this->openAPINullablesSetToNull, 'emailVerificationCode');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('emailVerificationCode', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['emailVerificationCode'] = $emailVerificationCode;

        return $this;
    }

    /**
     * Gets emailVerificationInput
     *
     * @return string|null
     */
    public function getEmailVerificationInput()
    {
        return $this->container['emailVerificationInput'];
    }

    /**
     * Sets emailVerificationInput
     *
     * @param string|null $emailVerificationInput emailVerificationInput
     *
     * @return self
     */
    public function setEmailVerificationInput($emailVerificationInput)
    {
        if (is_null($emailVerificationInput)) {
            array_push($this->openAPINullablesSetToNull, 'emailVerificationInput');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('emailVerificationInput', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['emailVerificationInput'] = $emailVerificationInput;

        return $this;
    }

    /**
     * Gets phoneVerificationCode
     *
     * @return string|null
     */
    public function getPhoneVerificationCode()
    {
        return $this->container['phoneVerificationCode'];
    }

    /**
     * Sets phoneVerificationCode
     *
     * @param string|null $phoneVerificationCode phoneVerificationCode
     *
     * @return self
     */
    public function setPhoneVerificationCode($phoneVerificationCode)
    {
        if (is_null($phoneVerificationCode)) {
            array_push($this->openAPINullablesSetToNull, 'phoneVerificationCode');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('phoneVerificationCode', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['phoneVerificationCode'] = $phoneVerificationCode;

        return $this;
    }

    /**
     * Gets phoneVerificationInput
     *
     * @return string|null
     */
    public function getPhoneVerificationInput()
    {
        return $this->container['phoneVerificationInput'];
    }

    /**
     * Sets phoneVerificationInput
     *
     * @param string|null $phoneVerificationInput phoneVerificationInput
     *
     * @return self
     */
    public function setPhoneVerificationInput($phoneVerificationInput)
    {
        if (is_null($phoneVerificationInput)) {
            array_push($this->openAPINullablesSetToNull, 'phoneVerificationInput');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('phoneVerificationInput', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['phoneVerificationInput'] = $phoneVerificationInput;

        return $this;
    }

    /**
     * Gets avatar
     *
     * @return string|null
     */
    public function getAvatar()
    {
        return $this->container['avatar'];
    }

    /**
     * Sets avatar
     *
     * @param string|null $avatar avatar
     *
     * @return self
     */
    public function setAvatar($avatar)
    {
        if (is_null($avatar)) {
            array_push($this->openAPINullablesSetToNull, 'avatar');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('avatar', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['avatar'] = $avatar;

        return $this;
    }

    /**
     * Gets notifications
     *
     * @return string[]|null
     */
    public function getNotifications()
    {
        return $this->container['notifications'];
    }

    /**
     * Sets notifications
     *
     * @param string[]|null $notifications notifications
     *
     * @return self
     */
    public function setNotifications($notifications)
    {
        if (is_null($notifications)) {
            throw new \InvalidArgumentException('non-nullable notifications cannot be null');
        }
        $this->container['notifications'] = $notifications;

        return $this;
    }

    /**
     * Gets medias
     *
     * @return string[]|null
     */
    public function getMedias()
    {
        return $this->container['medias'];
    }

    /**
     * Sets medias
     *
     * @param string[]|null $medias medias
     *
     * @return self
     */
    public function setMedias($medias)
    {
        if (is_null($medias)) {
            throw new \InvalidArgumentException('non-nullable medias cannot be null');
        }
        $this->container['medias'] = $medias;

        return $this;
    }

    /**
     * Gets views
     *
     * @return \Tripartie\Tpdk\Model\View[]
     */
    public function getViews()
    {
        return $this->container['views'];
    }

    /**
     * Sets views
     *
     * @param \Tripartie\Tpdk\Model\View[] $views views
     *
     * @return self
     */
    public function setViews($views)
    {
        if (is_null($views)) {
            throw new \InvalidArgumentException('non-nullable views cannot be null');
        }
        $this->container['views'] = $views;

        return $this;
    }

    /**
     * Gets createdAt
     *
     * @return \DateTime|null
     */
    public function getCreatedAt()
    {
        return $this->container['createdAt'];
    }

    /**
     * Sets createdAt
     *
     * @param \DateTime|null $createdAt createdAt
     *
     * @return self
     */
    public function setCreatedAt($createdAt)
    {
        if (is_null($createdAt)) {
            throw new \InvalidArgumentException('non-nullable createdAt cannot be null');
        }
        $this->container['createdAt'] = $createdAt;

        return $this;
    }

    /**
     * Gets updatedAt
     *
     * @return \DateTime|null
     */
    public function getUpdatedAt()
    {
        return $this->container['updatedAt'];
    }

    /**
     * Sets updatedAt
     *
     * @param \DateTime|null $updatedAt updatedAt
     *
     * @return self
     */
    public function setUpdatedAt($updatedAt)
    {
        if (is_null($updatedAt)) {
            throw new \InvalidArgumentException('non-nullable updatedAt cannot be null');
        }
        $this->container['updatedAt'] = $updatedAt;

        return $this;
    }

    /**
     * Gets consentMailNotification
     *
     * @return bool
     */
    public function getConsentMailNotification()
    {
        return $this->container['consentMailNotification'];
    }

    /**
     * Sets consentMailNotification
     *
     * @param bool $consentMailNotification consentMailNotification
     *
     * @return self
     */
    public function setConsentMailNotification($consentMailNotification)
    {
        if (is_null($consentMailNotification)) {
            throw new \InvalidArgumentException('non-nullable consentMailNotification cannot be null');
        }
        $this->container['consentMailNotification'] = $consentMailNotification;

        return $this;
    }

    /**
     * Gets consentMailAds
     *
     * @return bool
     */
    public function getConsentMailAds()
    {
        return $this->container['consentMailAds'];
    }

    /**
     * Sets consentMailAds
     *
     * @param bool $consentMailAds consentMailAds
     *
     * @return self
     */
    public function setConsentMailAds($consentMailAds)
    {
        if (is_null($consentMailAds)) {
            throw new \InvalidArgumentException('non-nullable consentMailAds cannot be null');
        }
        $this->container['consentMailAds'] = $consentMailAds;

        return $this;
    }

    /**
     * Gets keys
     *
     * @return string[]
     */
    public function getKeys()
    {
        return $this->container['keys'];
    }

    /**
     * Sets keys
     *
     * @param string[] $keys keys
     *
     * @return self
     */
    public function setKeys($keys)
    {
        if (is_null($keys)) {
            throw new \InvalidArgumentException('non-nullable keys cannot be null');
        }
        $this->container['keys'] = $keys;

        return $this;
    }

    /**
     * Gets organization
     *
     * @return string|null
     */
    public function getOrganization()
    {
        return $this->container['organization'];
    }

    /**
     * Sets organization
     *
     * @param string|null $organization organization
     *
     * @return self
     */
    public function setOrganization($organization)
    {
        if (is_null($organization)) {
            array_push($this->openAPINullablesSetToNull, 'organization');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('organization', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['organization'] = $organization;

        return $this;
    }

    /**
     * Gets username
     *
     * @return string|null
     */
    public function getUsername()
    {
        return $this->container['username'];
    }

    /**
     * Sets username
     *
     * @param string|null $username A visual identifier that represents this user.
     *
     * @return self
     */
    public function setUsername($username)
    {
        if (is_null($username)) {
            throw new \InvalidArgumentException('non-nullable username cannot be null');
        }
        $this->container['username'] = $username;

        return $this;
    }

    /**
     * Gets salt
     *
     * @return string|null
     */
    public function getSalt()
    {
        return $this->container['salt'];
    }

    /**
     * Sets salt
     *
     * @param string|null $salt salt
     *
     * @return self
     */
    public function setSalt($salt)
    {
        if (is_null($salt)) {
            array_push($this->openAPINullablesSetToNull, 'salt');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('salt', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['salt'] = $salt;

        return $this;
    }

    /**
     * Gets userIdentifier
     *
     * @return string|null
     */
    public function getUserIdentifier()
    {
        return $this->container['userIdentifier'];
    }

    /**
     * Sets userIdentifier
     *
     * @param string|null $userIdentifier userIdentifier
     *
     * @return self
     */
    public function setUserIdentifier($userIdentifier)
    {
        if (is_null($userIdentifier)) {
            throw new \InvalidArgumentException('non-nullable userIdentifier cannot be null');
        }
        $this->container['userIdentifier'] = $userIdentifier;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


