<?php
/**
 * BrandingApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Tripartie\Tpdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Tripartie
 *
 * Our API suite for the **Resolution Center** and the **Safe Checkout** features. Simple, yet elegant web interfaces for your convenience. One request away from your first automated resolution or safe-checkout.
 *
 * The version of the OpenAPI document: 2.0.178
 * Contact: noc@tripartie.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Tripartie\Tpdk\Test\Api;

use \Tripartie\Tpdk\Configuration;
use \Tripartie\Tpdk\ApiException;
use \Tripartie\Tpdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * BrandingApiTest Class Doc Comment
 *
 * @category Class
 * @package  Tripartie\Tpdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BrandingApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for apiOrganizationsIdPatch
     *
     * Update your Organization details, branding or parameters.
     *
     */
    public function testApiOrganizationsIdPatch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiOrganizationsIdiconDelete
     *
     * Unset your Organization Icon.
     *
     */
    public function testApiOrganizationsIdiconDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiOrganizationsIdiconPost
     *
     * Upload your Organization Icon.
     *
     */
    public function testApiOrganizationsIdiconPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiOrganizationsIdlogoDelete
     *
     * Unset your Organization Logo.
     *
     */
    public function testApiOrganizationsIdlogoDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiOrganizationsIdlogoPost
     *
     * Upload your Organization logo.
     *
     */
    public function testApiOrganizationsIdlogoPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
