<?php
/**
 * NotificationApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Tripartie\Tpdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Tripartie
 *
 * Our API suite for the **Resolution Center** and the **Safe Checkout** features. Simple, yet elegant web interfaces for your convenience. One request away from your first automated resolution or safe-checkout.
 *
 * The version of the OpenAPI document: 2.0.178
 * Contact: noc@tripartie.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Tripartie\Tpdk\Test\Api;

use \Tripartie\Tpdk\Configuration;
use \Tripartie\Tpdk\ApiException;
use \Tripartie\Tpdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * NotificationApiTest Class Doc Comment
 *
 * @category Class
 * @package  Tripartie\Tpdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class NotificationApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for apiPersonasIdnotificationsGetCollection
     *
     * Retrieve pending notifications for Persona.
     *
     */
    public function testApiPersonasIdnotificationsGetCollection()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiPersonasPersonaIdnotificationsIdPatch
     *
     * Mark as read/unread a notification for Persona.
     *
     */
    public function testApiPersonasPersonaIdnotificationsIdPatch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiUsersIdnotificationsGetCollection
     *
     * Retrieves the collection of Notification resources..
     *
     */
    public function testApiUsersIdnotificationsGetCollection()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiUsersUserIdnotificationsIdPatch
     *
     * Mark as read/unread a notification for User.
     *
     */
    public function testApiUsersUserIdnotificationsIdPatch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
