<?php
/**
 * ResolutionCenterApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Tripartie\Tpdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Tripartie
 *
 * Our API suite for the **Resolution Center** and the **Safe Checkout** features. Simple, yet elegant web interfaces for your convenience. One request away from your first automated resolution or safe-checkout.
 *
 * The version of the OpenAPI document: 2.0.28
 * Contact: noc@tripartie.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Tripartie\Tpdk\Test\Api;

use \Tripartie\Tpdk\Configuration;
use \Tripartie\Tpdk\ApiException;
use \Tripartie\Tpdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ResolutionCenterApiTest Class Doc Comment
 *
 * @category Class
 * @package  Tripartie\Tpdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ResolutionCenterApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for apiDisputesGetCollection
     *
     * Retrieves the collection of Dispute resources..
     *
     */
    public function testApiDisputesGetCollection()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiDisputesPost
     *
     * Draft a standalone Dispute.
     *
     */
    public function testApiDisputesPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiDisputesUlidDelete
     *
     * Abandon claims on Dispute.
     *
     */
    public function testApiDisputesUlidDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiDisputesUlidGet
     *
     * Retrieves a Dispute resource..
     *
     */
    public function testApiDisputesUlidGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiDisputesUlidPatch
     *
     * Update the Dispute.
     *
     */
    public function testApiDisputesUlidPatch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiDisputesUlidevaluationsPost
     *
     * Submit an Evaluation for the Dispute.
     *
     */
    public function testApiDisputesUlidevaluationsPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiDisputesUlidevidencesGetCollection
     *
     * Retrieve all Evidences in Dispute.
     *
     */
    public function testApiDisputesUlidevidencesGetCollection()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiDisputesUlidevidencesIdDelete
     *
     * Withdraw an Evidence from a Dispute.
     *
     */
    public function testApiDisputesUlidevidencesIdDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiDisputesUlidevidencesIdmediaPost
     *
     * Upload attachment in regard of described Evidence.
     *
     */
    public function testApiDisputesUlidevidencesIdmediaPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiDisputesUlidevidencesPost
     *
     * Submit an Evidence to the Dispute case.
     *
     */
    public function testApiDisputesUlidevidencesPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiDisputesUlidparcelsGetCollection
     *
     * Retrieves the collection of Parcel resources..
     *
     */
    public function testApiDisputesUlidparcelsGetCollection()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiDisputesUlidparcelsIdDelete
     *
     * Removes the Parcel resource..
     *
     */
    public function testApiDisputesUlidparcelsIdDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiDisputesUlidparcelsIdGet
     *
     * Read single parcel state.
     *
     */
    public function testApiDisputesUlidparcelsIdGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiDisputesUlidparcelsPost
     *
     * Creates a Parcel resource..
     *
     */
    public function testApiDisputesUlidparcelsPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiOffersUlidmediasPost
     *
     * Upload a picture for a given Offer.
     *
     */
    public function testApiOffersUlidmediasPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
