<?php
/**
 * SafeCheckoutApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Tripartie\Tpdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Tripartie
 *
 * Our API suite for the **Resolution Center** and the **Safe Checkout** features. Simple, yet elegant web interfaces for your convenience. One request away from your first automated resolution or safe-checkout.
 *
 * The version of the OpenAPI document: 2.0.194
 * Contact: noc@tripartie.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Tripartie\Tpdk\Test\Api;

use \Tripartie\Tpdk\Configuration;
use \Tripartie\Tpdk\ApiException;
use \Tripartie\Tpdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SafeCheckoutApiTest Class Doc Comment
 *
 * @category Class
 * @package  Tripartie\Tpdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SafeCheckoutApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for apiOffersGetCollection
     *
     * Read issued Offers.
     *
     */
    public function testApiOffersGetCollection()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiOffersPost
     *
     * Create an Offer and retrieve url.
     *
     */
    public function testApiOffersPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiOffersUlidGet
     *
     * Read an Offer.
     *
     */
    public function testApiOffersUlidGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiOffersUlidmediasIdDelete
     *
     * Removes the Media resource..
     *
     */
    public function testApiOffersUlidmediasIdDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiOffersUlidmediasPost
     *
     * Upload a picture for a given Offer.
     *
     */
    public function testApiOffersUlidmediasPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiOffersUlidtransactionsGetCollection
     *
     * Retrieve Payment Intents for Offer.
     *
     */
    public function testApiOffersUlidtransactionsGetCollection()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiOffersUlidtransactionsIdevaluationsPost
     *
     * Submit an Evaluation for the Offer.
     *
     */
    public function testApiOffersUlidtransactionsIdevaluationsPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiOffersUlidtransactionsPost
     *
     * Create a Payment Intent for Offer.
     *
     */
    public function testApiOffersUlidtransactionsPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiPersonasIdoffersDelete
     *
     * Revoke an Offer for given Persona.
     *
     */
    public function testApiPersonasIdoffersDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiPersonasIdoffersGetCollection
     *
     * List or Search Offers for given Persona.
     *
     */
    public function testApiPersonasIdoffersGetCollection()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiPersonasIdoffersPatch
     *
     * Update an Offer for given Persona.
     *
     */
    public function testApiPersonasIdoffersPatch()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiPersonasIdoffersPost
     *
     * Create an Offer for given Persona.
     *
     */
    public function testApiPersonasIdoffersPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiTransactionsGetCollection
     *
     * Retrieves the collection of Transaction resources..
     *
     */
    public function testApiTransactionsGetCollection()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiTransactionsUliddisputeDelete
     *
     * Abandon claims on Dispute.
     *
     */
    public function testApiTransactionsUliddisputeDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiTransactionsUliddisputeGet
     *
     * Read Dispute from existing Transaction.
     *
     */
    public function testApiTransactionsUliddisputeGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiTransactionsUliddisputePatch
     *
     * Interact with a Dispute.
     *
     */
    public function testApiTransactionsUliddisputePatch()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiTransactionsUliddisputePost
     *
     * Open a Dispute related to existing Transaction.
     *
     */
    public function testApiTransactionsUliddisputePost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiTransactionsUlidparcelsGetCollection
     *
     * Read shipments from Transaction.
     *
     */
    public function testApiTransactionsUlidparcelsGetCollection()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiTransactionsUlidparcelsIdDelete
     *
     * Withdraw shipment from Transaction.
     *
     */
    public function testApiTransactionsUlidparcelsIdDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiTransactionsUlidparcelsPost
     *
     * Manually declare package shipped for Transaction.
     *
     */
    public function testApiTransactionsUlidparcelsPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
